export const  navdatalink = [
    {
        id:1,
        title:"Home",
        link:"home"
    },
    {
        id:2,
        title:"About",
        link:"about"
    },
    {
        id:3,
        title:"Project",
        link:"project"
    },
    {
        id:4,
        title:"Service",
        link:"service"
    },
    {
        id:5,
        title:"Contact",
        link:"contact"
    }
]